sudo: false
addons:
  apt:
    packages: 
    - libdb5.1-dev
language: python
python: 3.4
env:
  - BERKELEYDB_DIR=/usr TOX_ENV=py34
install:
  - pip install -r requirements/tox.txt
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coverage combine
  - coverage report
  - coveralls
