language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements/develop.txt
    - pip install coveralls
    - python setup.py develop
script:
    - py.test --cov binlog --cov-report= tests/unit
    - cd docs/
    - sphinx-build -W -b html -d /tmp/doctress . /tmp/html
    - cd ..
after_success:
    - coveralls
