language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
install:
    - pip install -r requirements/tox.txt
    - pip install coveralls
    - python setup.py develop
script:
    - py.test --cov binlog tests/unit
    - cd docs/
    - sphinx-build -W -b html -d /tmp/doctress . /tmp/html
after_success:
    - coveralls
